GET http://localhost:3001/jedi/view
###
GET http://localhost:3001/jedi/view/:jedi_id
###
POST http://localhost:3001/jedi/add
content-type: application/json
###
PATCH http://localhost:3001/jedi/update/:jedi_id
content-type: application/json
###
DELETE http://localhost:3001/jedi/delete/:jedi_id